artifacts_root: artifacts 

data_ingestion:
  root_dir: artifacts/data_ingestion
  ingested_data_file: artifacts/data_ingestion/data/raw.csv

data_validation:
  root_dir: artifacts/data_validation
  input_data_path: artifacts/data_ingestion/data/raw.csv
  valid_train_file: artifacts/data_validation/valid_data/train.csv
  valid_test_file: artifacts/data_validation/valid_data/test.csv